=pod

=head1 How to run these benchmarks:

First, some prerequisites are:

     make
     modern C and C++ compilers (gcc, clang or similar)
     boost
     google sparsehash
     qt
     libjudy
     libkyotocabinet
     libleveldb
     librocksdb
     libpython3

Now, run:

    $ git submodule update --init --recursive
    $ emacs apps.txt # select assotiative arrays you are interested in
    $ make
    $ ./bench.py
    $ ./make_chart_data.py < output | ./make_html.py

Your charts are now in charts.html.

=head1 Copyright Information

 Written by Nick Welch in 2010.
 Forked by Tessil in 2016.
 Forked by Aleksey Cheusov in 2020.
 No copyright.  This work is dedicated to the public domain.
 For full details, see http://creativecommons.org/publicdomain/zero/1.0/

=cut
